### ISSUE TITLE
[Home] 후원사 카드 내부 로고 배치 수정

### ISSUE THREAD

**Issue by wisemuji** [droidknights/DroidKnightsApp#161]
## Kind (Required)
- Improvement

## Overview (Required)

- 기존 후원사 카드 내부 로고 배치 수정
- 자동/무한 스크롤 기능 제거
  - 이 기능은 더 이상 유효하지 않으므로 제거합니다.

## [Before]

<img width="429" alt="image" src="https://github.com/droidknights/DroidKnights2023_App/assets/32327475/2b0056fc-0fba-4fb2-8301-9a04662aaf6b">

## [After]

- [디자인](https://www.figma.com/file/FL7CdEyPjvhkJrtYEHAbXn/2023-Droid-Knights-App-_-KEB?type=design&node-id=426%3A904&mode=design&t=sPHKM9YQdIfU4bOl-1)
<img width="629" alt="image" src="https://github.com/droidknights/DroidKnights2023_App/assets/32327475/c5cffdf0-619a-487c-bca8-1539806891b3">

**Comment by koreatlwls** [comment]
🙋‍♀️🙋🙋‍♂️
