### ISSUE TITLE
[build-logic] Type-safe project dependencies on Gradle

### ISSUE THREAD

**Issue by laco-dev** [droidknights/DroidKnightsApp#17]
## Kind (Required)
- Improvement

## Overview (Required)
- module 의존성 추가하기 위한 타입 안정성 기능

## Links
- https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:type-safe-project-accessors

**Comment by l2hyunwoo** [comment]
🙋‍♂️

**Comment by laco-dev** [comment]
@l2hyunwoo 
안녕하세요, 이슈 잘 부탁드립니다. 궁금한게 있으면 남겨주세요. 🙏🏻
