### ISSUE TITLE
[북마크] 앱이 종료된 이후에도 북마크한 세션 아이디를 유지한다

### ISSUE THREAD

**Issue by laco-dev** [droidknights/DroidKnightsApp#202]
## Kind (Required)
- Feature

## Overview (Required)
- 앱이 종료된 이후, 마지막에 저장한 북마크 아이디를 유지해야 합니다.
- 북마크 아이디를 저장하는 방법은 자유이지만, 간단하게 구현해도 괜찮습니다.

**Comment by l2hyunwoo** [comment]
🙋‍♂️

**Comment by wisemuji** [comment]
@l2hyunwoo 감사합니다!

참고로 아래 이슈가 닫힌 이후에 작업하는 것도 고려해보시면 좋을 것 같아요. 해당 이슈를 진행하기 위해 DataStore 의존성을 추가하여 작업 진행 예정이십니다.
https://github.com/droidknights/DroidKnights2023_App/issues/147#issuecomment-1682240394

**Comment by wisemuji** [comment]
@l2hyunwoo 언급했던 이슈가 Closed 되어 알려드립니다! 작업에 참고 부탁드려요.

**Comment by l2hyunwoo** [comment]
https://github.com/droidknights/DroidKnights2023_App/pull/234

이 이슈가 진행이 되어야 기능 테스트도 진행할 수 있을 것 같네요 (물론 Unit Test로 검증할 수야 있겠습니다만 UI 구현된 곳에서도 검증이 필요할 수도 있을 것 같아서요)

**Comment by l2hyunwoo** [comment]
이전 작업이 머지되어 작업 시작해보도록 하겠습니다.

**Comment by wisemuji** [comment]
@l2hyunwoo 네! 진행하시는데 어려움이 있으시다면 편하게 알려주세요.
