### ISSUE TITLE
[세션] 복수의 발표자 대응

### ISSUE THREAD

**Issue by wisemuji** [droidknights/DroidKnightsApp#283]
## Kind (Required)

- Improvement

## Overview (Required)

- 현재는 세션 상세 화면에서 단일 발표자만 보여지도록 구현되어 있음
- 복수의 발표자가 있는 case에 대해 정상 동작하도록 수정 필요
```kotlin
@Composable
private fun SessionDetailContent(session: Session) {
    ...
    SessionDetailSpeaker(session.speakers.first())
    ...
}
```

## Links

- https://github.com/droidknights/DroidKnightsApp/blob/fd733e7ad728b6e8596724a696a20fb1a669cf75/widget/src/main/kotlin/com/droidknights/app/widget/WidgetSessionCard.kt#L52
- https://github.com/droidknights/DroidKnightsApp/blob/fd733e7ad728b6e8596724a696a20fb1a669cf75/feature/session/src/main/java/com/droidknights/app/feature/session/SessionDetailScreen.kt#L164

**Comment by ParkJong-Hun** [comment]
🙋‍♂️해보고싶습니다

**Comment by ParkJong-Hun** [comment]
☝️일단 언제든 PR 날릴 준비는 되어 있습니다만, Assignee 설정이 안되어 있기 때문에 작성하지는 않겠습니다.

**Comment by taehwandev** [comment]
@ParkJong-Hun 아직 외부 참여기간이 아닙니다 정리해서 요청드리겠습니다.

**Comment by ParkJong-Hun** [comment]
@taehwandev 그렇군요. 기다리겠습니다.

**Comment by ParkJong-Hun** [comment]
@taehwandev 
안녕하세요. #297 를 확인했습니다.
이 이슈 담당해도 괜찮을까요?
