### ISSUE TITLE
[디자인] 디자인 최신화

### ISSUE THREAD

**Issue by KimReady** [droidknights/DroidKnightsApp#289]
## Kind (Required)
- Design

## Overview (Required)
- 피그마 디자인과 간격, 컬러, 모양 등 다르게 구현된 부분이 다소 발견되어 전체적으로 스펙과 구현을 일치시키는 작업을 진행해요.

## Links

- [피그마](https://www.figma.com/design/FL7CdEyPjvhkJrtYEHAbXn/2023-Droid-Knights-App-_-KEB?node-id=1-381&t=wf87R1NkVuvpHCcM-0)

**Comment by JeonK1** [comment]
🙋‍♂️
