### ISSUE TITLE
[컨트리뷰터] 2024년도의 컨트리뷰터 필터링이 필요합니다.

### ISSUE THREAD

**Issue by laco-dev** [droidknights/DroidKnightsApp#298]
## Kind (Required)
- Feature

## Overview (Required)
- 드로이드나이츠 레포지터리를 작년과 동일하게 운영하면서, 작년도 기여자가 같이 포함되었습니다.
- 2024년도의 기여자에 대해서만 필터링이 필요할 것 같습니다.

**Comment by rhkrwngud445** [comment]
🙋‍♂️ 담당하고 싶습니다!
