### ISSUE TITLE
[Improvement] Type Safe Navigation 적용

### ISSUE THREAD

**Issue by l2hyunwoo** [droidknights/DroidKnightsApp#300]
## Kind (Required)
- Improvement

## Overview (Required)

- 기존 route(String) 기반의 네비게이션 방식에서 Type Safe 네비게이션으로의 전환을 건의드립니다. (androidx-navigation 2.8.x 대)

## Links

-[Navigation Compose meet Type Safety](https://medium.com/androiddevelopers/navigation-compose-meet-type-safety-e081fb3cf2f8)

**Comment by l2hyunwoo** [comment]
✋🏻

**Comment by taehwandev** [comment]
@l2hyunwoo Labels 2024 붙여주세요.

**Comment by l2hyunwoo** [comment]
@taehwandev 알겠습니다!
