### ISSUE TITLE
[Proposal] 스크린샷 테스트

### ISSUE THREAD

**Issue by ParkJong-Hun** [droidknights/DroidKnightsApp#304]
## Kind (Required)

- Proposal

## Overview (Required)

- Roborazzi나 Compose Preview Screenshot Testing으로 모든 컴포넌트, 화면의 Preview를 PR의 CI 단계에서 스크린샷으로 저장하고 Diff를 봇이 코멘트하게 하면 UI 대응과 의도치 않는 변경을 보다 수월하게 확인이 가능해요.
  - 브랜치에 스크린샷을 저장하도록 하면 브랜치 목록이 조금 리포지토리가 더러워지지만 가장 코스트가 좋아요.

## Links
- https://github.com/takahirom/roborazzi
- https://developer.android.com/studio/preview/compose-screenshot-testing

**Comment by KwakEuiJin** [comment]
🙋‍♂️

**Comment by taehwandev** [comment]
@KwakEuiJin 진행부탁드려요.

**Comment by KwakEuiJin** [comment]
@taehwandev 넵 감사합니다☺️
