### ISSUE TITLE
[Improvement] Kotlin 2.0으로 Migration

### ISSUE THREAD

**Issue by l2hyunwoo** [droidknights/DroidKnightsApp#306]
## Kind (Required)
- Improvement

## Overview (Required)

- 드로이드나이츠 레포지터리 내 코드를 참고하는 팀/개발자분들이 많은 것으로 알고 있어서, 해당 레포지터리에 2.0 버전을 적용한다면 이후에 이 코드를 참고해서 마이그레이션 하는 분들께 도움이 될 수 있을 것 같습니다.
- 또한 Kotlin 2.0.0을 활용하여 Kotlin이 관장하는 Compose Compiler를 적용하고 MutableStateFlow에 field를 적용하여 Kotlin 2.0에서 사용할 수 있는 문법적 특성을 공유합니다.
- 안정성이 보장되어있지 않은 업데이트여서 main브랜치가 아닌 **별도의 브랜치에 머지**하는 것으로 작업하면 좋을 것 같습니다.

## Links

- [Kotlin’s Explicit Backing Fields](https://noob-programmer.medium.com/kotlins-explicit-backing-fields-a-cleaner-way-to-work-with-mutablestateflow-926e2dbc946e)
- [Kotlin 2.0 Migration](https://medium.com/@l2hyunwoo/kotlin-2-0%EC%9C%BC%EB%A1%9C-%EB%A7%88%EC%9D%B4%EA%B7%B8%EB%A0%88%EC%9D%B4%EC%85%98%ED%95%98%EA%B8%B0-1742f294df51)

**Comment by l2hyunwoo** [comment]
✋🏻

**Comment by taehwandev** [comment]
어차피 다음 드나앱에서는 진행하게 될 내용이라 당장 필요한 부분은 아닐것 같아요.

**Comment by taehwandev** [comment]
@l2hyunwoo 진행하시면 별도 브랜치로 처리해두겠습니다.
적용 후 동작에 대한 이상한 부분이 있는지 한번 확인하고 공유부탁드려요.


만약 큰 이상이 없다면 메인에 머지하는것도 고려해보겠습니다. cc. @wisemuji @KimReady
