### ISSUE TITLE
[개선] UI 파일을 단위별로 분리해봅니다.

### ISSUE THREAD

**Issue by taehwandev** [droidknights/DroidKnightsApp#308]
## Kind (Required)

UI 컴포넌트가 하나의 파일로 몰아져있습니다. 이를 몇가지 단위로 분리해봅니다.
- 공통 컴포넌트를 찾고, UI를 분리
- 하나의 파일 안에 위치한 UI를 기능단위로 묶어서 분리해보기

**Comment by tmdgh1592** [comment]
🙋‍♂️ 담당하고 싶습니다!
