### ISSUE TITLE
[버그] 홈 화면의 후원 기업 로고가 너무 크게 보여 잘립니다.

### ISSUE THREAD

**Issue by ParkJong-Hun** [droidknights/DroidKnightsApp#316]
**Overview (Required)**
- 의도한 디자인인지 모르겠지만, 제트 브레인 사와 헤이 딜러 사 이외의 모든 회사의 로고가 너무 크게 보여서, 로고의 일부분이 잘리며 디지털스러움이 부각되어 있어서 위화감을 느껴 보고드립니다.

**Steps To Reproduce**

1. 앱을 실행
2. 홈 화면에서 아래로 스크롤해 후원 카드뷰를 표시

**Expected behavior**

- 로고가 모두 팔각형 모양 내에 담길 것.
- 이미지에 되도록 계단 현상이 일어나지 않을 것.

**Screenshots**
<img src="https://github.com/droidknights/DroidKnightsApp/assets/81838716/bae335b0-246d-40a0-b175-5cc10e3dd843" width="300"/>

**Env:**
 - Device: Galaxy S24
 - OS: Android 14.0(One UI 6.1)
 - App Version or the branch : main 브랜치([c081d4e](https://github.com/droidknights/DroidKnightsApp/commit/c081d4e172f580fff6895da9d4d4db5f9a02996e)
 ·)

**Comment by KimReady** [comment]
#288 에서 해결한 이슈인데, 최신 메인 브랜치에서 재현 되시나요? 저는 해결된 것으로 보입니다.

**Comment by ParkJong-Hun** [comment]
@KimReady 
죄송합니다, 캐쉬 문제로 빌드 클리어 후 다시 빌드하니 해결되었습니다.
해당 이슈는 클로즈하겠습니다.
