### ISSUE TITLE
[Docs]: Android Gradle plugin and Android Studio compatibility

### ISSUE THREAD

**Issue by KwakEuiJin** [droidknights/DroidKnightsApp#322]
## Kind (Required)
- 현재 AGP 버전은 8.3.2 버전이며, 이에 대응되는 최소 안드로이드 스튜디오 버전은 Iguana 버전입니다.

## Overview (Required)
- 따라서 README.md 파일의 IDE를 Giraffe에서 Android Studio Iguana 변경하고자합니다.

## Links
[관련 공식 문서 링크](https://developer.android.com/studio/releases#android_gradle_plugin_and_android_studio_compatibility)

**Comment by taehwandev** [comment]
최신버전으로 명시합니다.
